language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  before_install:
  - gem install bundler:2.1.4
  - bundle update mimemagic
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: mDJUBI3JEYMRNGYQtgesPSViDH46W3a0MYvwKR302U+TkogA1/PIBRgrsIaA4eHIr1/mbKL7oVClsG5rvxc4eO98shKbNIVmcxLmNj0WfafR2Y+6+VWo6SPIu1FgauoEMFBwwJ+PFxII6oYXg706aiTl1nZ5WvV8FJ4AGgDZjO1wfNg7AdiouvZDyjq0AvfrOpAljbSZk3mXWSARBg0I6gJXHJpVUbHi/iB2fjMjrqkJ8lchP2tV6rCqw0c5ynbCA4ld7s9617Q07lfcis62kW8JCEMBxTcX91Gom9w2VMJg3hi71WFKj/WvMd96iGUOJet1HieIrJzu7mBI9keotNBII5G43el19o6WzmUzDhOnew8K2qOsVFblVBEvfkDGrWTPo858HIg80XtEMOZ+W9kK0ZSlgtIPLZuveV06fPTrPskr09EzKHYMTn/TGIEmSQHBw8koGUgWsn95NiydygJx+o/7adVDZewSu+Z79jEm0VtD0obDT/hFA6j8dL979iaHcByzCW4P91MOHur/P65sCR7lHKOCrBuiax3Flglw5QshH6GGj7Yy19uCz/7/S/G5D1E1Hgy7oPajsihj+OwvaqoFEcW0YaqOT8iOsFM+GKJlFHELtZw0bh5xpRUmA1ps4f+wRGyTSsK/90tl9SqV6BEzPACvZQv3TuusI04=
  on:
    all_branches: true
  app: secure-citadel-15128
  run: rails db:migrate
env:
  global:
    secure: RguW6i/VoAUsZG4KBf1oouQVAd2WPaPEFnUNf87gEj+hF91anu0zLLwcJRPz1DCyg4cTIw6DixcfXjFe+98aegSWOEiBd6eq/3+KsYwrUviB8p+Gek+L9/kzy0fvaWnUupDxt/7gIfO0/Y7O3/SveQ9uLtShtWxITKeq3uXqIroqQmPY0jzVHKrYK07KGsfoCPvjM8czfr8iKurODWl/CoUu9km7SjGfmxvLwZ+SU5tP/dttlg9XEuFIpwZOdnOtRkn3yZz07RQltdoQFQ8HHZ9bzZH8fYho0f57JPWJPp6j1QZfnFFPH/d34QBPPhajJ2f5yjipM/I4FDeB9ex7fLRK5RZyfj5l/3vG+6U0SNobO4E53I0VjyHJpLZmmZLZW4TjR0IvdEUO0UcQCThVlIX+6MIsxztTKXVSLA2FyzuhkXJF96v8f4vcdcTWIO4PkErHcU73gthU1tZVF3/7Q92RdzRZwDKFvRZ7/xkvLN4v1ch0PBKg9KqtFB4B8cmeumMkUFGpLdkuKw0QC3DSS2wdqjm5HXB+232P+jUWz9mM9gJdMNIN+ify6aFiq7F9TcQDEwazN33SR6J3/toMTjMS0zJ71xBvpO9sml8r2Ate5y+BU68lKrIS6gZtgv+vaJgc5iF80xirk8AJSJ/1tDtZBtWrVETOVL5BhLfJfo4=
